### ISSUE TITLE
Socket issue

### ISSUE THREAD

**Issue by iamalperen** [mucahidyazar/mucahid.dev#4]
There is a socket issue on page. Please check the console errors 

`Failed to load resource: the server responded with a status of 504 ()
GET https://mucahid.dev/api/socket?EIO=4&t=NxtL7TB&transport=polling 504
`

**Comment by mucahidyazar** [comment]
I didn't get it but the socket was working on my local correctly but it was not working on the production. I didn't understand o much but the problem is socket can not work correctly on the next.js server. Next.js restricts the socket request on prod as I understand. So I removed the socket feature for now. And the problem is solved. But I will develop it later. Thanks for your feedback.
